### ISSUE TITLE
No helm chart for Benthos

### ISSUE THREAD

**Issue by Demmyart** [redpanda-data/redpanda-connect-helm-chart#95]
Hi, could you update the link for the helm chart, cuz it could not be found

`Error: looks like "https://benthosdev.github.io/benthos-helm-chart/" is not a valid chart repository or cannot be reached: failed to fetch https://benthosdev.github.io/benthos-helm-chart/index.yaml : 404 Not Found``

**Comment by charlie-haley** [comment]
Hey @Demmyart, sorry, it looks like the old pages deployment broke in the process of migrating to the Redpanda org. If you use the new chart repository, it will work as usual! `https://benthosdev.github.io/charts/`

**Comment by Demmyart** [comment]
oh, yes, it works, thank you!
