### ISSUE TITLE
Updates after redpanda acquisition?

### ISSUE THREAD

**Issue by dersvenhesse** [redpanda-data/redpanda-connect-helm-chart#96]
Hello,
I'm just curious, will this repository still be maintained and updated after the redpanda acquisition? If so, will there be new chart repositories?

Thanks in advance
Sven

**Comment by charlie-haley** [comment]
Hi @dersvenhesse,

Yes, the chart will still be maintained as usual! It's possible the chart could be migrated or moved into another repo, but I'll be sure to have that communicated as best as possible if it does happen. Also, I'll try to keep the old charts live in the event of this happening as to not break existing deployments

**Comment by dersvenhesse** [comment]
Thank you very much, I'm happy to hear that.
